export const countries = [
    { name: 'Afghanistan', code: 'AF' },
    { name: 'Albania', code: 'AL' },
    { name: 'Algeria', code: 'DZ' },
    { name: 'Andorra', code: 'AD' },
    { name: 'Angola', code: 'AO' },
    { name: 'Antigua and Barbuda', code: 'AG' },
    { name: 'Argentina', code: 'AR' },
    { name: 'Armenia', code: 'AM' },
    { name: 'Australia', code: 'AU' },
    { name: 'Austria', code: 'AT' },
    { name: 'Azerbaijan', code: 'AZ' },
    { name: 'Bahamas', code: 'BS' },
    { name: 'Bahrain', code: 'BH' },
    { name: 'Bangladesh', code: 'BD' },
    { name: 'Barbados', code: 'BB' },
    { name: 'Belarus', code: 'BY' },
    { name: 'Belgium', code: 'BE' },
    { name: 'Belize', code: 'BZ' },
    { name: 'Benin', code: 'BJ' },
    { name: 'Bhutan', code: 'BT' },
    { name: 'Bolivia', code: 'BO' },
    { name: 'Bosnia and Herzegovina', code: 'BA' },
    { name: 'Botswana', code: 'BW' },
    { name: 'Brazil', code: 'BR' },
    { name: 'Brunei', code: 'BN' },
    { name: 'Bulgaria', code: 'BG' },
    { name: 'Burkina Faso', code: 'BF' },
    { name: 'Burundi', code: 'BI' },
    { name: 'Cambodia', code: 'KH' },
    { name: 'Cameroon', code: 'CM' },
    { name: 'Canada', code: 'CA' },
    { name: 'Cape Verde', code: 'CV' },
    { name: 'Central African Republic', code: 'CF' },
    { name: 'Chad', code: 'TD' },
    { name: 'Chile', code: 'CL' },
    { name: 'China', code: 'CN' },
    { name: 'Colombia', code: 'CO' },
    { name: 'Comoros', code: 'KM' },
    { name: 'Congo (Brazzaville)', code: 'CG' },
    { name: 'Congo (Kinshasa)', code: 'CD' },
    { name: 'Costa Rica', code: 'CR' },
    { name: 'Croatia', code: 'HR' },
    { name: 'Cuba', code: 'CU' },
    { name: 'Cyprus', code: 'CY' },
    { name: 'Czech Republic', code: 'CZ' },
    { name: 'Denmark', code: 'DK' },
    { name: 'Djibouti', code: 'DJ' },
    { name: 'Dominica', code: 'DM' },
    { name: 'Dominican Republic', code: 'DO' },
    { name: 'East Timor', code: 'TL' },
    { name: 'Ecuador', code: 'EC' },
    { name: 'Egypt', code: 'EG' },
    { name: 'El Salvador', code: 'SV' },
    { name: 'Equatorial Guinea', code: 'GQ' },
    { name: 'Eritrea', code: 'ER' },
    { name: 'Estonia', code: 'EE' },
    { name: 'Ethiopia', code: 'ET' },
    { name: 'Fiji', code: 'FJ' },
    { name: 'Finland', code: 'FI' },
    { name: 'France', code: 'FR' },
    { name: 'Gabon', code: 'GA' },
    { name: 'Gambia', code: 'GM' },
    { name: 'Georgia', code: 'GE' },
    { name: 'Germany', code: 'DE' },
    { name: 'Ghana', code: 'GH' },
    { name: 'Greece', code: 'GR' },
    { name: 'Grenada', code: 'GD' },
    { name: 'Guatemala', code: 'GT' },
    { name: 'Guinea', code: 'GN' },
    { name: 'Guinea-Bissau', code: 'GW' },
    { name: 'Guyana', code: 'GY' },
    { name: 'Haiti', code: 'HT' },
    { name: 'Honduras', code: 'HN' },
    { name: 'Hungary', code: 'HU' },
    { name: 'Iceland', code: 'IS' },
    { name: 'India', code: 'IN' },
    { name: 'Indonesia', code: 'ID' },
    { name: 'Iran', code: 'IR' },
    { name: 'Iraq', code: 'IQ' },
    { name: 'Ireland', code: 'IE' },
    { name: 'Israel', code: 'IL' },
    { name: 'Italy', code: 'IT' },
    { name: 'Ivory Coast', code: 'CI' },
    { name: 'Jamaica', code: 'JM' },
    { name: 'Japan', code: 'JP' },
    { name: 'Jordan', code: 'JO' },
    { name: 'Kazakhstan', code: 'KZ' },
    { name: 'Kenya', code: 'KE' },
    { name: 'Kiribati', code: 'KI' },
    { name: 'Kuwait', code: 'KW' },
    { name: 'Kyrgyzstan', code: 'KG' },
    { name: 'Laos', code: 'LA' },
    { name: 'Latvia', code: 'LV' },
    { name: 'Lebanon', code: 'LB' },
    { name: 'Lesotho', code: 'LS' },
    { name: 'Liberia', code: 'LR' },
    { name: 'Libya', code: 'LY' },
    { name: 'Liechtenstein', code: 'LI' },
    { name: 'Lithuania', code: 'LT' },
    { name: 'Luxembourg', code: 'LU' },
    { name: 'Macedonia', code: 'MK' },
    { name: 'Madagascar', code: 'MG' },
    { name: 'Malawi', code: 'MW' },
    { name: 'Malaysia', code: 'MY' },
    { name: 'Maldives', code: 'MV' },
    { name: 'Mali', code: 'ML' },
    { name: 'Malta', code: 'MT' },
    { name: 'Marshall Islands', code: 'MH' },
    { name: 'Mauritania', code: 'MR' },
    { name: 'Mauritius', code: 'MU' },
    { name: 'Mexico', code: 'MX' },
    { name: 'Micronesia', code: 'FM' },
    { name: 'Moldova', code: 'MD' },
    { name: 'Monaco', code: 'MC' },
    { name: 'Mongolia', code: 'MN' },
    { name: 'Montenegro', code: 'ME' },
    { name: 'Morocco', code: 'MA' },
    { name: 'Mozambique', code: 'MZ' },
    { name: 'Myanmar', code: 'MM' },
    { name: 'Namibia', code: 'NA' },
    { name: 'Nauru', code: 'NR' },
    { name: 'Nepal', code: 'NP' },
    { name: 'Netherlands', code: 'NL' },
    { name: 'New Zealand', code: 'NZ' },
    { name: 'Nicaragua', code: 'NI' },
    { name: 'Niger', code: 'NE' },
    { name: 'Nigeria', code: 'NG' },
    { name: 'North Korea', code: 'KP' },
    { name: 'Norway', code: 'NO' },
    { name: 'Oman', code: 'OM' },
    { name: 'Pakistan', code: 'PK' },
    { name: 'Palau', code: 'PW' },
    { name: 'Panama', code: 'PA' },
    { name: 'Papua New Guinea', code: 'PG' },
    { name: 'Paraguay', code: 'PY' },
    { name: 'Peru', code: 'PE' },
    { name: 'Philippines', code: 'PH' },
    { name: 'Poland', code: 'PL' },
    { name: 'Portugal', code: 'PT' },
    { name: 'Qatar', code: 'QA' },
    { name: 'Romania', code: 'RO' },
    { name: 'Russia', code: 'RU' },
    { name: 'Rwanda', code: 'RW' },
    { name: 'Saint Kitts and Nevis', code: 'KN' },
    { name: 'Saint Lucia', code: 'LC' },
    { name: 'Saint Vincent and the Grenadines', code: 'VC' },
    { name: 'Samoa', code: 'WS' },
    { name: 'San Marino', code: 'SM' },
    { name: 'Sao Tome and Principe', code: 'ST' },
    { name: 'Saudi Arabia', code: 'SA' },
    { name: 'Senegal', code: 'SN' },
    { name: 'Serbia', code: 'RS' },
    { name: 'Seychelles', code: 'SC' },
    { name: 'Sierra Leone', code: 'SL' },
    { name: 'Singapore', code: 'SG' },
    { name: 'Slovakia', code: 'SK' },
    { name: 'Slovenia', code: 'SI' },
    { name: 'Solomon Islands', code: 'SB' },
    { name: 'Somalia', code: 'SO' },
    { name: 'South Africa', code: 'ZA' },
    { name: 'South Korea', code: 'KR' },
    { name: 'South Sudan', code: 'SS' },
    { name: 'Spain', code: 'ES' },
    { name: 'Sri Lanka', code: 'LK' },
    { name: 'Sudan', code: 'SD' },
    { name: 'Suriname', code: 'SR' },
    { name: 'Sweden', code: 'SE' },
    { name: 'Switzerland', code: 'CH' },
    { name: 'Syria', code: 'SY' },
    { name: 'Taiwan', code: 'TW' },
    { name: 'Tajikistan', code: 'TJ' },
    { name: 'Tanzania', code: 'TZ' },
    { name: 'Thailand', code: 'TH' },
    { name: 'Togo', code: 'TG' },
    { name: 'Tonga', code: 'TO' },
    { name: 'Trinidad and Tobago', code: 'TT' },
    { name: 'Tunisia', code: 'TN' },
    { name: 'Turkey', code: 'TR' },
    { name: 'Turkmenistan', code: 'TM' },
    { name: 'Tuvalu', code: 'TV' },
    { name: 'Uganda', code: 'UG' },
    { name: 'Ukraine', code: 'UA' },
    { name: 'United Arab Emirates', code: 'AE' },
    { name: 'United Kingdom', code: 'GB' },
    { name: 'United States', code: 'US' },
    { name: 'Uruguay', code: 'UY' },
    { name: 'Uzbekistan', code: 'UZ' },
    { name: 'Vanuatu', code: 'VU' },
    { name: 'Vatican City', code: 'VA' },
    { name: 'Venezuela', code: 'VE' },
    { name: 'Vietnam', code: 'VN' },
    { name: 'Yemen', code: 'YE' },
    { name: 'Zambia', code: 'ZM' },
    { name: 'Zimbabwe', code: 'ZW' },
  ];

export const countriesGerman = [
    { name: 'Afghanistan', code: 'AF' },
    { name: 'Albanien', code: 'AL' },
    { name: 'Algerien', code: 'DZ' },
    { name: 'Andorra', code: 'AD' },
    { name: 'Angola', code: 'AO' },
    { name: 'Antigua und Barbuda', code: 'AG' },
    { name: 'Argentinien', code: 'AR' },
    { name: 'Armenien', code: 'AM' },
    { name: 'Australien', code: 'AU' },
    { name: 'Österreich', code: 'AT' },
    { name: 'Aserbaidschan', code: 'AZ' },
    { name: 'Bahamas', code: 'BS' },
    { name: 'Bahrain', code: 'BH' },
    { name: 'Bangladesch', code: 'BD' },
    { name: 'Barbados', code: 'BB' },
    { name: 'Weißrussland', code: 'BY' },
    { name: 'Belgien', code: 'BE' },
    { name: 'Belize', code: 'BZ' },
    { name: 'Benin', code: 'BJ' },
    { name: 'Bhutan', code: 'BT' },
    { name: 'Bolivien', code: 'BO' },
    { name: 'Bosnien und Herzegowina', code: 'BA' },
    { name: 'Botswana', code: 'BW' },
    { name: 'Brasilien', code: 'BR' },
    { name: 'Brunei', code: 'BN' },
    { name: 'Bulgarien', code: 'BG' },
    { name: 'Burkina Faso', code: 'BF' },
    { name: 'Burundi', code: 'BI' },
    { name: 'Kambodscha', code: 'KH' },
    { name: 'Kamerun', code: 'CM' },
    { name: 'Kanada', code: 'CA' },
    { name: 'Kap Verde', code: 'CV' },
    { name: 'Zentralafrikanische Republik', code: 'CF' },
    { name: 'Tschad', code: 'TD' },
    { name: 'Chile', code: 'CL' },
    { name: 'China', code: 'CN' },
    { name: 'Kolumbien', code: 'CO' },
    { name: 'Komoren', code: 'KM' },
    { name: 'Kongo (Brazzaville)', code: 'CG' },
    { name: 'Kongo (Kinshasa)', code: 'CD' },
    { name: 'Costa Rica', code: 'CR' },
    { name: 'Kroatien', code: 'HR' },
    { name: 'Kuba', code: 'CU' },
    { name: 'Zypern', code: 'CY' },
    { name: 'Tschechien', code: 'CZ' },
    { name: 'Dänemark', code: 'DK' },
    { name: 'Dschibuti', code: 'DJ' },
    { name: 'Dominica', code: 'DM' },
    { name: 'Dominikanische Republik', code: 'DO' },
    { name: 'Osttimor', code: 'TL' },
    { name: 'Ecuador', code: 'EC' },
    { name: 'Ägypten', code: 'EG' },
    { name: 'El Salvador', code: 'SV' },
    { name: 'Äquatorialguinea', code: 'GQ' },
    { name: 'Eritrea', code: 'ER' },
    { name: 'Estland', code: 'EE' },
    { name: 'Äthiopien', code: 'ET' },
    { name: 'Fidschi', code: 'FJ' },
    { name: 'Finnland', code: 'FI' },
    { name: 'Frankreich', code: 'FR' },
    { name: 'Gabun', code: 'GA' },
    { name: 'Gambia', code: 'GM' },
    { name: 'Georgien', code: 'GE' },
    { name: 'Deutschland', code: 'DE' },
    { name: 'Ghana', code: 'GH' },
    { name: 'Griechenland', code: 'GR' },
    { name: 'Grenada', code: 'GD' },
    { name: 'Guatemala', code: 'GT' },
    { name: 'Guinea', code: 'GN' },
    { name: 'Guinea-Bissau', code: 'GW' },
    { name: 'Guyana', code: 'GY' },
    { name: 'Haiti', code: 'HT' },
    { name: 'Honduras', code: 'HN' },
    { name: 'Ungarn', code: 'HU' },
    { name: 'Island', code: 'IS' },
    { name: 'Indien', code: 'IN' },
    { name: 'Indonesien', code: 'ID' },
    { name: 'Iran', code: 'IR' },
    { name: 'Irak', code: 'IQ' },
    { name: 'Irland', code: 'IE' },
    { name: 'Israel', code: 'IL' },
    { name: 'Italien', code: 'IT' },
    { name: 'Elfenbeinküste', code: 'CI' },
    { name: 'Jamaika', code: 'JM' },
    { name: 'Japan', code: 'JP' },
    { name: 'Jordanien', code: 'JO' },
    { name: 'Kasachstan', code: 'KZ' },
    { name: 'Kenia', code: 'KE' },
    { name: 'Kiribati', code: 'KI' },
    { name: 'Kuwait', code: 'KW' },
    { name: 'Kirgisistan', code: 'KG' },
    { name: 'Laos', code: 'LA' },
    { name: 'Lettland', code: 'LV' },
    { name: 'Libanon', code: 'LB' },
    { name: 'Lesotho', code: 'LS' },
    { name: 'Liberia', code: 'LR' },
    { name: 'Libyen', code: 'LY' },
    { name: 'Liechtenstein', code: 'LI' },
    { name: 'Litauen', code: 'LT' },
    { name: 'Luxemburg', code: 'LU' },
    { name: 'Mazedonien', code: 'MK' },
    { name: 'Madagaskar', code: 'MG' },
    { name: 'Malawi', code: 'MW' },
    { name: 'Malaysia', code: 'MY' },
    { name: 'Malediven', code: 'MV' },
    { name: 'Mali', code: 'ML' },
    { name: 'Malta', code: 'MT' },
    { name: 'Marshallinseln', code: 'MH' },
    { name: 'Mauretanien', code: 'MR' },
    { name: 'Mauritius', code: 'MU' },
    { name: 'Mexiko', code: 'MX' },
    { name: 'Mikronesien', code: 'FM' },
    { name: 'Moldawien', code: 'MD' },
    { name: 'Monaco', code: 'MC' },
    { name: 'Mongolei', code: 'MN' },
    { name: 'Montenegro', code: 'ME' },
    { name: 'Marokko', code: 'MA' },
    { name: 'Mosambik', code: 'MZ' },
    { name: 'Myanmar', code: 'MM' },
    { name: 'Namibia', code: 'NA' },
    { name: 'Nauru', code: 'NR' },
    { name: 'Nepal', code: 'NP' },
    { name: 'Niederlande', code: 'NL' },
    { name: 'Neuseeland', code: 'NZ' },
    { name: 'Nicaragua', code: 'NI' },
    { name: 'Niger', code: 'NE' },
    { name: 'Nigeria', code: 'NG' },
    { name: 'Nordkorea', code: 'KP' },
    { name: 'Norwegen', code: 'NO' },
    { name: 'Oman', code: 'OM' },
    { name: 'Pakistan', code: 'PK' },
    { name: 'Palau', code: 'PW' },
    { name: 'Panama', code: 'PA' },
    { name: 'Papua-Neuguinea', code: 'PG' },
    { name: 'Paraguay', code: 'PY' },
    { name: 'Peru', code: 'PE' },
    { name: 'Philippinen', code: 'PH' },
    { name: 'Polen', code: 'PL' },
    { name: 'Portugal', code: 'PT' },
    { name: 'Katar', code: 'QA' },
    { name: 'Rumänien', code: 'RO' },
    { name: 'Russland', code: 'RU' },
    { name: 'Ruanda', code: 'RW' },
    { name: 'St. Kitts und Nevis', code: 'KN' },
    { name: 'St. Lucia', code: 'LC' },
    { name: 'St. Vincent und die Grenadinen', code: 'VC' },
    { name: 'Samoa', code: 'WS' },
    { name: 'San Marino', code: 'SM' },
    { name: 'São Tomé und Príncipe', code: 'ST' },
    { name: 'Saudi-Arabien', code: 'SA' },
    { name: 'Senegal', code: 'SN' },
    { name: 'Serbien', code: 'RS' },
    { name: 'Seychellen', code: 'SC' },
    { name: 'Sierra Leone', code: 'SL' },
    { name: 'Singapur', code: 'SG' },
    { name: 'Slowakei', code: 'SK' },
    { name: 'Slowenien', code: 'SI' },
    { name: 'Salomonen', code: 'SB' },
    { name: 'Somalia', code: 'SO' },
    { name: 'Südafrika', code: 'ZA' },
    { name: 'Südkorea', code: 'KR' },
    { name: 'Südsudan', code: 'SS' },
    { name: 'Spanien', code: 'ES' },
    { name: 'Sri Lanka', code: 'LK' },
    { name: 'Sudan', code: 'SD' },
    { name: 'Suriname', code: 'SR' },
    { name: 'Schweden', code: 'SE' },
    { name: 'Schweiz', code: 'CH' },
    { name: 'Syrien', code: 'SY' },
    { name: 'Taiwan', code: 'TW' },
    { name: 'Tadschikistan', code: 'TJ' },
    { name: 'Tansania', code: 'TZ' },
    { name: 'Thailand', code: 'TH' },
    { name: 'Togo', code: 'TG' },
    { name: 'Tonga', code: 'TO' },
    { name: 'Trinidad und Tobago', code: 'TT' },
    { name: 'Tunesien', code: 'TN' },
    { name: 'Türkei', code: 'TR' },
    { name: 'Turkmenistan', code: 'TM' },
    { name: 'Tuvalu', code: 'TV' },
    { name: 'Uganda', code: 'UG' },
    { name: 'Ukraine', code: 'UA' },
    { name: 'Vereinigte Arabische Emirate', code: 'AE' },
    { name: 'Vereinigtes Königreich', code: 'GB' },
    { name: 'Vereinigte Staaten', code: 'US' },
    { name: 'Uruguay', code: 'UY' },
    { name: 'Usbekistan', code: 'UZ' },
    { name: 'Vanuatu', code: 'VU' },
    { name: 'Vatikanstadt', code: 'VA' },
    { name: 'Venezuela', code: 'VE' },
    { name: 'Vietnam', code: 'VN' },
    { name: 'Jemen', code: 'YE' },
    { name: 'Sambia', code: 'ZM' },
    { name: 'Simbabwe', code: 'ZW' },
];
